### ISSUE TITLE
DPW Activity Manager - Dropdown List

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/DPW_and_CW_Activity_Applications#114] opened 2016-05-05 17:10 UTC
In DEV, if a user has access to more that one activity, only one activity is visible in the dropdown.  Please correct this so that all activities for that user are visible and selectable.

**Comment by taojun545** [comment] 2016-05-05 17:19
It works good on my account. Could you show me which user has the issue?

**Comment by alanfoster99** [comment] 2016-05-05 17:20
Alan.foster
David.thompson2

Alan E. Foster
Business Analyst, KCI Technologies, Inc. – Geospatial Practice
1.410.316.0812
alan.foster@kci.commailto:alan.foster@kci.com

[cid:image001.jpg@01D1A6D0.CFD20130]http://kci.com/

Chief, Data Management Division, Baltimore City Department of Public Works
1.410.396.0022
alan.foster@baltimorecity.govmailto:alan.foster@baltimorecity.gov

**Comment by taojun545** [comment] 2016-05-05 17:22
I checked Dev Administration Portal, and both users only have one activity access.

**Comment by taojun545** [comment] 2016-05-05 17:29
I think the issue is on Admin Portal.

I saw you were using User Directory to add user, but it only assign one activity to you.

You can click Roles on the left menu, and click the checkbox to assign multiple activities to you.

**Comment by alanfoster99** [comment] 2016-05-05 17:29
Well, I just added myself back to the SSO Investigation activity, and it deleted me from Lateral CCTV.  So the issue is with the admin portal.

Alan E. Foster
Business Analyst, KCI Technologies, Inc. – Geospatial Practice
1.410.316.0812
alan.foster@kci.commailto:alan.foster@kci.com

[cid:image001.jpg@01D1A6D1.7C031ED0]http://kci.com/

Chief, Data Management Division, Baltimore City Department of Public Works
1.410.396.0022
alan.foster@baltimorecity.govmailto:alan.foster@baltimorecity.gov

**Comment by taojun545** [comment] 2016-05-05 17:32
Yes, you are right. I will take a look at the issue on Admin Portal.

**Comment by alanfoster99** [comment] 2016-05-05 17:33
Got it -- thanks.  Dropping priority to medium, since there is work around identified.

**Comment by taojun545** [comment] 2016-05-05 19:41
The Admin Portal issue has been fixed on dev. @JMurk 

The issue is on both "DPW Activity Manager" and "Cityworks Activity Browser", which should allow to assign multiple roles to one user.

When adding user from User Directory, it will also remove other existing roles. It is correct on Mobile Application, which only allow one role for each user. But for other two above, it is wrong. So I changed the code on dev, and it should be correct for all now.

**Comment by JMurk** [comment] 2016-06-22 13:17
Confirmed in dev, please push to prod.

**Comment by taojun545** [comment] 2016-06-23 16:00
@JMurk Could you sync the table "dbo.User" in cityUsers database between dev and prod? There is a new field "Organization" for that table.

**Comment by JMurk** [comment] 2016-06-23 16:18
Done

**Comment by taojun545** [comment] 2016-06-23 17:08
Updated in prod.

**Comment by JMurk** [comment] 2016-06-24 16:32
Confirmed complete

**Closed as completed by JMurk** 2016-06-24 16:32 UTC
Labels: bug, moderate priority
